version: "3"

services:
  appweb:
    container_name: examsapp
    restart: always
    build: .
    ports:
    - "3000:3000"
    links:
      - mongodb

  mongodb:
    container_name: mongoDataBase1
    image: mongo
    ports:
      - "27018:27017"